### PR TITLE
proxy: Do not assign duplicate slot IDs

### LINKED ISSUE #266: httpd fails to get signatures when using p11-kit-proxy + engine_pkcs11 and new devices are added
The apache server (httpd) fails to get signatures from the PKCS#11 module when new devices are added.

It seems to be caused by a mismatch of the device mapped to the session handle obtained before a device is added and the device mapped by p11-kit-proxy to the handle after a device is added.

In a more specific scenario, if httpd is configured to use keys from a SoftHSM token and a smart card reader (using the openSC module) is connected before starting httpd, it doesn't work: It successfully starts, but fails to get signatures from the SoftHSM. This seems to be related to different list of slots/modules seen by the processes before and after forking and changing the user.

A minimal reproducer is available in: https://github.com/ansasaki/toolbox/blob/master/p11-kit-reproducer/fork-change-slot.c which is a slightly modified version of https://github.com/OpenSC/libp11/blob/master/tests/fork-change-slot.c

The reproducer requires OpenSSL, SoftHSM (from https://github.com/opendnssec/SoftHSMv2), openSC, a smart card reader, a smart card,  and engine_pkcs11 (from https://github.com/OpenSC/libp11). The steps to reproduce are:

1. Compile the reproducer:
```
$ gcc fork-change-slot.c -o fork_change_slot -lcrypto
```

2. Create a SoftHSM token and populate with keys
  - download https://github.com/ansasaki/toolbox/blob/master/setup-softhsm-rsa.sh
  - run:
```
$ source setup-softhsm-rsa.sh
```

3. Run the reproducer passing the PKCS#11 URI for the key in the softhsm and the p11-kit-proxy module (note: the pid of the child process will be printed; it will be necessary for the step 5)
```
$ fork_change_slot "pkcs11:token=softhsm;object=test;type=private?pin-value=1234" &
```

4. Connect the smart card reader with the smart card (make sure ``pcscd`` is running)

5. Send the ``SIGUSR1`` signal to the child process:
```
$ kill -USR1 <pid>
```
**Actual Results:**
```
pid <pid>: EVP_SignFinal generated errors:
140099411543040:error:8207A060:PKCS#11 module:pkcs11_private_encrypt:Key handle invalid:p11_rsa.c:116:
child <pid> exited with status 1
```

**Expected Results**
```
pid <pid1>: 256-byte signature created
pid <pid1>: Signature matched
child <pid1> exited with status 0
pid <pid2> 256-byte signature created
pid <pid2>: Signature matched
```

### PR DESCRIPTION
**Pull request by ansasaki**
This PR supersedes #281  

Previously, when assigning the slot IDs to the mapping, it could happen that new slots were listed by the module before slots previously seen. In this case duplicate slot IDs would be assigned to different slots.

This change makes all the reused slot IDs to be assigned before the new slot IDs. It also tries to make the slot IDs monotonically crescent.

A reproducer test case was added.

Fixes #266

### CODE REVIEW

File: p11-kit/proxy.c [hunk 1]
```diff
@@ -279,29 +277,59 @@ proxy_list_slots (Proxy *py, Mapping *mappings, unsigned int n_mappings)
...
+			/* Remember the largest ID assigned */
+			for (j = 0; j < n_mappings; ++j) {
+				if (mappings[j].wrap_slot > max_id)
+					max_id = mappings[j].wrap_slot;
+			}
+
+			/* The ID for the next new mapping will be greater than any
+			 * previously assigned ID */
+			++max_id;
+			if (max_id > MAPPING_OFFSET)
```
Comment (ueno) [inline p11-kit/proxy.c]: any reason to subtract MAPPING_OFFSET while it is added back below?

File: p11-kit/proxy.c [hunk 2]
```diff
@@ -279,29 +277,59 @@ proxy_list_slots (Proxy *py, Mapping *mappings, unsigned int n_mappings)
...
 				}
-				py->mappings[py->n_mappings].funcs = funcs;
-				py->mappings[py->n_mappings].wrap_slot =
-					(n_mappings == 0 || j == n_mappings) ?
-					py->n_mappings + MAPPING_OFFSET :
-					mappings[j].wrap_slot;
-				py->mappings[py->n_mappings].real_slot = slots[i];
-				++py->n_mappings;
+				if (n_mappings == 0 || j == n_mappings)
+					is_new_mapping[i] = true;
```
Comment (ueno) [inline p11-kit/proxy.c]: can we simply maintain max_id in the Proxy structure, and increment and assign a new ID here?

Comment (ansasaki) [reply p11-kit/proxy.c]: It would be better and make things easier. I tried to make it to work without changing the structures.

I'll change this.

File: p11-kit/proxy.c (hunk 1 above)
Comment (ansasaki) [reply p11-kit/proxy.c]: The reason is to keep the ID's sequential and not waste ``MAPPING_OFFSET`` ID's. But I agree it wasn't implemented in the best way. I think the best would be to keep the last ID assigned in the proxy structure.

File: p11-kit/proxy.c (hunk 2 above)
Comment (ansasaki) [reply p11-kit/proxy.c]: I moved the ``max_id`` to the proxy structure as ``last_id``, which holds the last assigned slot ID. Then we can assign unique ID's and store the used value in ``proxy->last_id``

File: p11-kit/proxy.c [hunk 3]
```diff
@@ -279,29 +278,46 @@ proxy_list_slots (Proxy *py, Mapping *mappings, unsigned int n_mappings)
...
 						break;
+					}
+				}
+				if (n_mappings == 0 || j == n_mappings)
+					is_new_mapping[i] = true;
+			}
+
+			/* And now add a mapping for each new slot */
+			for (i = 0; i < count; ++i) {
+				if (is_new_mapping[i]) {
```
Comment (ueno) [inline p11-kit/proxy.c]: nit: I suspect this loop can be simpler if you record slot IDs instead of boolean flags.

Comment (ansasaki) [reply p11-kit/proxy.c]: Makes sense, I'll change it.

Comment (ansasaki) [reply p11-kit/proxy.c]: Changed it to store the ID's.
