### PR TITLE
library: Use dedicated locale object for printing error

### LINKED ISSUE #147: Test suite fails on Alpine Linux x86_64
````
=======================================
   p11-kit 0.23.10: ./test-suite.log
=======================================

# TOTAL: 50
# PASS:  46
# SKIP:  0
# XFAIL: 0
# FAIL:  4
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-message
==================

1..1
Segmentation fault
FAIL test-message (exit status: 139)

FAIL: test-conf
===============

1..15
Segmentation fault
FAIL test-conf (exit status: 139)

FAIL: test-parser
=================

1..11
Segmentation fault
FAIL test-parser (exit status: 139)

FAIL: test-save
===============

1..15
Segmentation fault
FAIL test-save (exit status: 139)
````

### PR DESCRIPTION
**Pull request by ueno**
Fixes #147

### CODE REVIEW

File: common/debug.c [hunk 1]
```diff
@@ -162,15 +163,9 @@ p11_debug_message_err (int flag,
...
-		/* As strerror_r() is being deprecated in POSIX:
-		 * http://austingroupbugs.net/view.php?id=655
-		 * we prefer to use strerror_l() with per-thread locale
-		 * argument as a thread-safe variant of strerror().
-		 */
-#if defined(HAVE_STRERROR_L) && defined(HAVE_USELOCALE)
-		loc = uselocale ((locale_t) 0);
-		if (loc != NULL)
-			strncpy (strerr, strerror_l (errnum, loc), sizeof (strerr));
+#if defined(HAVE_STRERROR_L) && defined(HAVE_NEWLOCALE)
```
Comment (ep69) [inline common/debug.c]: I am not really proficient with autotools and stuff, but is it somehow guaranteed that having `HAVE_LOCALE_H` defined would lead to having `HAVE_NEWLOCALE` defined?

Comment (ueno) [reply common/debug.c]: Thank you for the review; I guess that is the case on most platforms these days. However, `newlocale()` seems to be missing on more platforms:
https://www.gnu.org/software/gnulib/manual/html_node/newlocale.html#newlocale
than `locale.h`:
https://www.gnu.org/software/gnulib/manual/html_node/locale_002eh.html#locale_002eh
